### ISSUE TITLE
Cap the count of elements being counted in a content block report so it doesn't time out

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-reports#105]
Reports of Content Blocks currently time out when there are thousands of items to count within a report. We should limit the counter at an amount which wont cause the report to time out. 

The counter is displayed as a number, cap the number at 1000 (just example) and signify there are more...  eg. 1000+

This is a issue which has been raised by a site which uses over 7000 content blocks.

Related issue https://github.com/dnadesign/silverstripe-elemental/issues/238

**Comment by robbieaverill** [comment]
To clarify, we have some dodgy logic causing the timeout in a custom report, but when we show a record count we might want to show 500+ instead of 3837384848 for example
