### ISSUE TITLE
Title unnecessarily cut off

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-reports#109]
When opening a report, the Title is unncessarily cut off:

![image](https://user-images.githubusercontent.com/167154/43177797-1e1527f8-901e-11e8-9418-e1b336484380.png)

There is a ton of room to show the title. What is more, it is really important to show it so you know exactly what the report list is about.

# Related PR
* [x] #110

**Comment by robbieaverill** [comment]
Ha! I just noticed this too

**Comment by maxime-rainville** [comment]
The `cms-content-header-info` is just missing the `flexbox-area-grow`. Other LeftAndMain controllers have it.
