### ISSUE TITLE
Filters params are empty 

### ISSUE THREAD

**Issue by ivoba** [silverstripe/silverstripe-reports#112]
When adding filters with the parameterFields method the params in the GET query are not reaching the sourceRecords method.

It seems that 

`$params = $request->param('filters') ?: [];`

returns null.

When using this code in sourceRecords the params are fetched:

```
 $request = Injector::inst()->get(HTTPRequest::class);
        $params  = $request->getVars();
        if (isset($params['filters'])) {
            $params = $params['filters'];
        }
```

So it seems param & params() method dont have the query GET params, only

> array (size=5)
>   'Action' => string 'show' (length=4)
>   'ID' => string 'App-Reports-MyReport' (length=25)
>   'OtherID' => null
>   'ReportClass' => string 'App-Reports-MyReport' (length=25)
>   'Controller' => string 'SilverStripe\Admin\AdminRootController' (length=38

My composer.json require block:

        "silverstripe/recipe-core": "^4.2",
        "silverstripe/admin": "^1.2",
        "silverstripe/asset-admin": "^1.2",
        "silverstripe/reports": "^4.2"

**Comment by robbieaverill** [comment]
Thanks @ivoba for reporting this issue. We've already fix this with https://github.com/silverstripe/silverstripe-reports/issues/99, and will be available in the next set of stable releases.
