### ISSUE TITLE
General usability Improvements to All Reports View

### ISSUE THREAD

**Issue by n8-dev** [silverstripe/silverstripe-reports#196]
### Description

There are 2 main improvements that are desireable.

## 1 Allow searching via either Title or Description with partialText matching.
Reason, its difficult to find your report when you have more than 1 pages worth (iirc 25+)

## 2 Set default_sort to be via title.
It currently is something else... Maybe via filepath or namespace.

To find a report that you want on load you have to click the title sort twice to have anything logical.

### Additional context or points of discussion

Appears that the base Gridfield here isn't using a default gridField scaffold class which makes custom override somewhat challenging.

Also we really should allow some of this details to be changed via `config` mechanics, and a couple extension hooks 🙏 

I may be able to get this PR under way; and therefore have checked the `intend to implement` for now

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/silverstripe/silverstripe-reports/pull/197
- https://github.com/silverstripe/developer-docs/pull/614

**Comment by GuySartorelli** [comment]
Sounds good to me.

**Comment by GuySartorelli** [comment]
Maybe split the PRs when you do it - have one for the filter functionality and a separate one for sorting. That way if there's any controversy with either piece of functionality, the other can still get merged in without waffling about.

**Comment by mfendeksilverstripe** [comment]
Fixed in https://github.com/silverstripe/silverstripe-reports/pull/197

**Comment by GuySartorelli** [comment]
PR merged.

@mfendeksilverstripe or @n8-dev can one of you please raise a PR for the `5` branch of https://github.com/silverstripe/developer-docs/ to add a note about this to the CMS 5.4 changelog?

Can be a full section if you think it warrants it, or just add a bullet point to the "other new features" section.

**Comment by mfendeksilverstripe** [comment]
Leaving this one with you @n8-dev

**Comment by n8-dev** [comment]
I'll try and do this next week!

Clean up the issue content too if needed etc

**Comment by n8-dev** [comment]
https://github.com/silverstripe/developer-docs/pull/614

**Comment by GuySartorelli** [comment]
PRs merged
