### ISSUE TITLE
"Filter" button text light grey

### ISSUE THREAD

**Issue by frankmullenger** [silverstripe/silverstripe-reports#41]
This CSS rule sets the "Filter" button text to light grey so it appears disabled:
https://github.com/silverstripe/silverstripe-framework/blob/master/admin/client/src/styles/legacy/_forms.scss#L315

The "Filter" button is added to any report that has parameterFields:
https://github.com/silverstripe-labs/silverstripe-reports/blob/3/code/Report.php#L237

Such as the CMS Broken Links Report:
https://github.com/silverstripe/silverstripe-cms/blob/master/code/reports/BrokenLinksReport.php#L127

**Comment by dhensby** [comment]
@frankmullenger are you happy to suggest a fix / open a PR?

**Comment by robbieaverill** [comment]
Closing, this isn't a problem in SilverStripe 4 anymore:

![image](https://user-images.githubusercontent.com/5170590/44122766-6d1fd1e8-a079-11e8-820c-f5485fde63ba.png)
