### ISSUE TITLE
Print and Export actions not working

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-reports#47]
Nothing seems to happen when the actions "Print" and "Export to CSV" are clicked
![image](https://cloud.githubusercontent.com/assets/555033/18500172/3bb374e6-7a99-11e6-9574-91ecd15cb75a.png)

**Comment by tractorcow** [comment]
I had a go at this, and it appears that the `onclick` handler for these buttons isn't being triggered in entwine.

**Comment by flamerohr** [comment]
Pull request made https://github.com/silverstripe/silverstripe-framework/pull/6191

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6191
