### ISSUE TITLE
CSV Export broken

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-reports#51]
https://github.com/silverstripe/silverstripe-cms/issues/1104

**Comment by nathanbrauer** [comment]
Any progress here?

**Comment by dhensby** [comment]
Is it still broken?

**Comment by nathanbrauer** [comment]
As far as I can tell

**Comment by robbieaverill** [comment]
I've tested this on SilverStripe 4.1.x and the correct columns are exported to the CSV. We're moving into a critical bug and security fix only phase for SilverStripe 3, so I'm going to close this.
