### ISSUE TITLE
Replace excluded_reports code with config use

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-reports#61]
Right now excluded_reports is managed as a directly-edited static property. We should change it to use config:

```
SilverStripe\Reports\Report:
  excluded_reports:  
    - 'SilverStripe\CMS\Reports\BrokenFilesReport'
    - 'SilverStripe\CMS\Reports\BrokenLinksReport'
    - 'SilverStripe\CMS\Reports\BrokenRedirectorPagesReport'
    - 'SilverStripe\CMS\Reports\BrokenVirtualPagesReport'
    - 'SilverStripe\CMS\Reports\EmptyPagesReport'
    - 'SilverStripe\CMS\Reports\RecentlyEditedReport'
```

 * Report.php needs to be corrected to use `$this->config()->excluded_reports` instead of `self::$excluded_reports`
 * `get_reports()` also needs to be fixed to use that config var too
 * `add_excluded_reports()` and `get_excluded_reports()` should probably be dropped in favour of just using config

**Comment by dhensby** [comment]
Is this safe to do in 3.x or do we want it in 4?

**Comment by sminnee** [comment]
Was expecting 4.

**Comment by robbieaverill** [comment]
PR at #80
