### ISSUE TITLE
Logo suggests the reports will show charts

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-reports#68]
The menu-logo suggests it will show charts and such. A bit confusing to a new user, maybe a simpler icon like a "page" or "csv" like is a better option?

**Comment by chillu** [comment]
@clarkepaul Happy for you to pick up, both otherwise closing

**Comment by clarkepaul** [comment]
Happy to receive recommendations for a better icon, you can find inspiration on https://thenounproject.com/ . For me, whether we use pie, bar, or line graph doesn't really make much difference but the icon needs to be visually distinct, have a connection to the title and contents of the area (which it does in an abstract way). A page icon is too close to Pages and CSV doesn't seem to fit right either as that could be used for any data. If you have ideas just send them straight to me and happy to discuss.
