### ISSUE TITLE
Report header is duplicated so second header isn't required

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-reports#91]
Can remove secondary heading "Report", unless anyone can think of a reason why it might be needed eg. reports which are a set of nested gridfields where you might need a second alternative heading.
<img width="295" alt="pasted_image_31_10_17__3_12_pm" src="https://user-images.githubusercontent.com/555033/32204416-eb15b2de-be4d-11e7-8382-7db516d6fc00.png">

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-reports/pull/97
