### ISSUE TITLE
Error in other language 

### ISSUE THREAD

**Issue by MohammaddReza** [silverstripe/silverstripe-reports#92]
when i change the Admin panel language (FA,Persian), the reports tab show this error:
`Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: SELECT DISTINCT count(DISTINCT "SiteTree"."ID") AS "Count" FROM "SiteTree" WHERE ("SiteTree"."LastEdited" > ?) HY000-1271: Illegal mix of collations for operation '>'
![2017-11-12_13-10-35](https://user-images.githubusercontent.com/6697319/32697677-29ef2358-c7ab-11e7-8c7b-8ea238f8f643.jpg)

GET /SilverStripe-cms-v4.0.0/admin/reports/

Line 64 in www\SilverStripe-cms-v4.0.0\vendor\silverstripe\framework\src\ORM\Connect\DBConnector.php
![2017-11-12_13-10-35](https://user-images.githubusercontent.com/6697319/32697681-56965386-c7ab-11e7-8376-3c6ff682fb24.jpg)
`

**Comment by chillu** [comment]
What collation are you using for this table? If you don't know how to find out, can you paste the output of `mysqldump -d -h localhost -u root -pmypassword --tables SiteTree databasename`? Replace with your user/pass/db details

**Comment by MohammaddReza** [comment]
im using utf8_general_ci

**Comment by chillu** [comment]
I'm able to reproduce this bug. It doesn't happen with German or Chinese, so might be a right-to-left thing.

**Comment by chillu** [comment]
Can you please describe the `SiteTree` table for me just to give us a bit more certainty about what we're looking at? So `DESCRIBE TABLE SiteTree`. Actually, `SHOW CREATE TABLE SiteTree` gives a bit more info.

**Comment by dnsl48** [comment]
Here's the explanation of why it happens: https://stackoverflow.com/questions/3029321/troubleshooting-illegal-mix-of-collations-error-in-mysql

The problem is most likely with the connection collation configuration. Though, can't say for sure without seeing the actual project configs.
